# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  cabrithonapiwebapi:
    image: cabrithonapiwebapi
    build:
      context: .
      dockerfile: src/CabriThonAPI.WebAPI/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5272:5272
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
